import {
  universes,
  universesRelations,
} from '@/entities/universe/universe.schema';
import { users, usersRelations } from '@/entities/user/user.schema';
import {
  galaxies,
  galaxiesRelations,
  solarSystems,
  solarSystemsRelations,
  stars,
  starsRelations,
  planets,
  planetsRelations,
  galaxyTypeEnum,
  spectralTypeEnum,
} from '@/entities/celestial/celestial.schema';
import { characters, charactersRelations } from '@/entities/character/character.schema';
import {
  constructs,
  constructsRelations,
  constructCategoryEnum,
} from '@/entities/construct/construct.schema';
import {
  maps,
  mapsRelations,
  gridCells,
  gridCellsRelations,
  mapRegions,
  mapRegionsRelations,
  gridCellFeatures,
  gridCellFeaturesRelations,
  regionSvgMappings,
  regionSvgMappingsRelations,
} from '@/entities/map/map.schema';
import {
  rootsOfPower,
  rootsOfPowerRelations,
  powerSystems,
  powerSystemsRelations,
  powerSubSystems,
  powerSubSystemsRelations,
  powerCategories,
  powerCategoriesRelations,
  powerAbilities,
  powerAbilitiesRelations,
  characterPowerAccess,
  characterPowerAccessRelations,
} from '@/entities/power-system/power-system.schema';
import {
  races,
  racesRelations,
  ethnicGroups,
  ethnicGroupsRelations,
} from '@/entities/race/race.schema';
import {
  regions,
  regionsRelations,
  regionTypeEnum,
  regionClimateEnum,
  regionFeatureTypeEnum,
} from '@/entities/region/region.schema';
import { religions, religionsRelations } from '@/entities/religion/religion.schema';

const schema = {
  users,
  usersRelations,
  universes,
  universesRelations,
  galaxies,
  galaxiesRelations,
  solarSystems,
  solarSystemsRelations,
  stars,
  starsRelations,
  planets,
  planetsRelations,
  characters,
  charactersRelations,
  constructs,
  constructsRelations,
  maps,
  mapsRelations,
  gridCells,
  gridCellsRelations,
  mapRegions,
  mapRegionsRelations,
  gridCellFeatures,
  gridCellFeaturesRelations,
  regionSvgMappings,
  regionSvgMappingsRelations,
  rootsOfPower,
  rootsOfPowerRelations,
  powerSystems,
  powerSystemsRelations,
  powerSubSystems,
  powerSubSystemsRelations,
  powerCategories,
  powerCategoriesRelations,
  powerAbilities,
  powerAbilitiesRelations,
  characterPowerAccess,
  characterPowerAccessRelations,
  races,
  racesRelations,
  ethnicGroups,
  ethnicGroupsRelations,
  regions,
  regionsRelations,
  regionTypeEnum,
  regionClimateEnum,
  regionFeatureTypeEnum,
  religions,
  religionsRelations,
  galaxyTypeEnum,
  spectralTypeEnum,
  constructCategoryEnum,
};

export default schema;
